### ISSUE TITLE
addKeyBinding not working in  4.0 

### ISSUE THREAD

**Issue by pramodbutte** [hakimel/reveal.js#2670]
Hi I have a function:

I have an index.js file which accompanies index.html. I include the index.js file in the index.html by

```javascript
        <script src="../../dist/reveal.js"></script>
	<script src="../../plugin/notes/notes.js"></script>
	<script src="../../plugin/markdown/markdown.js"></script>
	<script src="../../plugin/highlight/highlight.js"></script>
	<script src="index.js"></script>
	<script>
		// More info about initialization & config:
		// - https://revealjs.com/initialization/
		// - https://revealjs.com/config/
		Reveal.initialize({
			hash: true,

			// Learn about plugins: https://revealjs.com/plugins/
			plugins: [RevealMarkdown, RevealHighlight, RevealNotes]
		});
```
this index.js file controls the svg animations which are triggered using 'r' key

```javascript
Reveal.addKeyBinding({ keyCode: 82, key: 'r', description: 'refresh' }, () => {
    //document.addEventListener('keydown', function (e) {
    //    if (e.key == "r") {
    h_slide = Reveal.getIndices().h
    v_slide = Reveal.getIndices().v
    if (h_slide == 10 && v_slide == 0) {

})
```

but I keep getting error:

```javascript
Uncaught TypeError: Reveal.addKeyBinding is not a function
    at index.js:1598
(anonymous) @ index.js:1598
```
What am I doing wrong?

**Comment by pramodbutte** [comment]
Nevermind, I had to add the index.js as dependencies during initialization.
